package project_branchapp;


import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JScrollPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jiepastor
 */
public class f_mainpage extends javax.swing.JFrame {

    /**
     * Creates new form f_mainpage
     */
    public f_mainpage() {
        initComponents();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        tp = new javax.swing.JTabbedPane();
        tp_balance = new javax.swing.JPanel();
        tp_b_scrollpane = new javax.swing.JScrollPane();
        tp_b_table = new javax.swing.JTable();
        tp_t_scrollpane = new javax.swing.JScrollPane();
        tp_t_table = new javax.swing.JTable();
        tp_t_spin_to_month = new javax.swing.JSpinner();
        tp_t_lbl_to = new javax.swing.JLabel();
        tp_t_lbl_from = new javax.swing.JLabel();
        tp_t_spin_from_month = new javax.swing.JSpinner();
        tp_t_spin_from_day = new javax.swing.JSpinner();
        tp_t_spin_to_day = new javax.swing.JSpinner();
        tp_t_spin_to_year = new javax.swing.JSpinner();
        tp_t_spin_from_year = new javax.swing.JSpinner();
        tp_t_btn_set = new javax.swing.JButton();
        tp_funds = new javax.swing.JPanel();
        tp_f_lbl_amount = new javax.swing.JLabel();
        tp_f_lbl_source = new javax.swing.JLabel();
        tp_f_lbl_dest = new javax.swing.JLabel();
        tp_f_t_dest = new javax.swing.JTextField();
        tp_f_t_amount = new javax.swing.JTextField();
        tp_f_t_source = new javax.swing.JComboBox<>();
        tp_f_scrollpane = new javax.swing.JScrollPane();
        tp_f_t_notes = new javax.swing.JTextArea();
        tp_f_lbl_notes = new javax.swing.JLabel();
        tp_f_btn_confirm = new javax.swing.JButton();
        tp_trans = new javax.swing.JPanel();
        tp_f_t_source1 = new javax.swing.JComboBox<>();
        tp_f_lbl_source1 = new javax.swing.JLabel();
        tp_f_t_amount1 = new javax.swing.JTextField();
        tp_f_lbl_amount1 = new javax.swing.JLabel();
        tp_f_btn_confirm2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        tp_f_lbl_source2 = new javax.swing.JLabel();
        tp_settings = new javax.swing.JPanel();
        tp_s_btn_info = new javax.swing.JButton();
        tp_s_btn_pass = new javax.swing.JButton();
        tp_s_btn_logout = new javax.swing.JButton();
        tp_s_btn_logout1 = new javax.swing.JButton();
        tp_s_btn_pass1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BBC Banking Services");

        jpanel.setBackground(new java.awt.Color(153, 0, 0));

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setForeground(new java.awt.Color(102, 102, 102));
        btn1.setText("PORTFOLIO");
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setForeground(new java.awt.Color(102, 102, 102));
        btn2.setText("TRANSFER FUNDS");
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setForeground(new java.awt.Color(102, 102, 102));
        btn4.setText("DEPOSIT/WITHDRAW");
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        tp.setBackground(new java.awt.Color(255, 255, 255));

        tp_balance.setBackground(new java.awt.Color(255, 255, 255));

        tp_b_scrollpane.setBackground(new java.awt.Color(255, 255, 255));

        tp_b_table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_b_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BANK", "ACCT NO", "ACCT TYPE", "STATUS", "BALANCE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tp_b_table.setGridColor(new java.awt.Color(255, 255, 255));
        tp_b_table.setRowHeight(30);
        tp_b_scrollpane.setViewportView(tp_b_table);

        tp_t_table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_t_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DI KO ALAM", "YUNG MGA DATA", "COLUMNS DITO", "EDIT NYO NLNG"
            }
        ));
        tp_t_table.setRowHeight(30);
        tp_t_scrollpane.setViewportView(tp_t_table);

        tp_t_spin_to_month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_lbl_to.setText("TO:");

        tp_t_lbl_from.setText("FROM:");

        tp_t_spin_from_month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_from_day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_to_day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_to_year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_from_year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_btn_set.setBackground(new java.awt.Color(0, 0, 0));
        tp_t_btn_set.setForeground(new java.awt.Color(255, 255, 255));
        tp_t_btn_set.setText("SET");

        javax.swing.GroupLayout tp_balanceLayout = new javax.swing.GroupLayout(tp_balance);
        tp_balance.setLayout(tp_balanceLayout);
        tp_balanceLayout.setHorizontalGroup(
            tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_balanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_b_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addComponent(tp_t_scrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addGroup(tp_balanceLayout.createSequentialGroup()
                        .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tp_balanceLayout.createSequentialGroup()
                                .addComponent(tp_t_lbl_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tp_t_spin_from_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tp_t_spin_from_day, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tp_t_spin_from_year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_balanceLayout.createSequentialGroup()
                                .addComponent(tp_t_lbl_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tp_t_spin_to_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tp_t_spin_to_day, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tp_t_spin_to_year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(tp_t_btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tp_balanceLayout.setVerticalGroup(
            tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_balanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_b_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_balanceLayout.createSequentialGroup()
                        .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tp_t_spin_from_day, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_from_month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_from_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_balanceLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tp_t_lbl_from)))
                        .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tp_t_spin_to_day, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_to_month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_to_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_balanceLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tp_t_lbl_to))))
                    .addComponent(tp_t_btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tp_t_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp.addTab("portfolio", tp_balance);

        tp_funds.setBackground(new java.awt.Color(255, 255, 255));

        tp_f_lbl_amount.setText("AMOUNT:");

        tp_f_lbl_source.setText("SOURCE ACCOUNT:");

        tp_f_lbl_dest.setText("DESTINATION ACCOUNT:");

        tp_f_t_dest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tp_f_t_amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tp_f_t_source.setBackground(new java.awt.Color(247, 247, 247));
        tp_f_t_source.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_f_t_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1234567890 - SAVINGS", "0987654321 - CHECKING" }));

        tp_f_t_notes.setColumns(20);
        tp_f_t_notes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_f_t_notes.setRows(5);
        tp_f_scrollpane.setViewportView(tp_f_t_notes);

        tp_f_lbl_notes.setText("NOTES:");

        tp_f_btn_confirm.setBackground(new java.awt.Color(0, 0, 0));
        tp_f_btn_confirm.setForeground(new java.awt.Color(255, 255, 255));
        tp_f_btn_confirm.setText("CONFIRM");

        javax.swing.GroupLayout tp_fundsLayout = new javax.swing.GroupLayout(tp_funds);
        tp_funds.setLayout(tp_fundsLayout);
        tp_fundsLayout.setHorizontalGroup(
            tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_fundsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_fundsLayout.createSequentialGroup()
                        .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_lbl_notes)
                            .addComponent(tp_f_lbl_amount))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tp_fundsLayout.createSequentialGroup()
                        .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tp_f_btn_confirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tp_f_scrollpane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_t_amount)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_fundsLayout.createSequentialGroup()
                                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tp_f_lbl_source)
                                    .addComponent(tp_f_t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tp_f_lbl_dest)
                                    .addComponent(tp_f_t_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))))
        );
        tp_fundsLayout.setVerticalGroup(
            tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_fundsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tp_f_lbl_source)
                    .addComponent(tp_f_lbl_dest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tp_f_t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tp_f_t_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tp_f_lbl_amount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_f_t_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tp_f_lbl_notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp_f_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tp_f_btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp.addTab("transfer funds", tp_funds);

        tp_trans.setBackground(new java.awt.Color(255, 255, 255));

        tp_f_t_source1.setBackground(new java.awt.Color(247, 247, 247));
        tp_f_t_source1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_f_t_source1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1234567890 - SAVINGS", "0987654321 - CHECKING" }));

        tp_f_lbl_source1.setText("SOURCE ACCOUNT:");

        tp_f_t_amount1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tp_f_lbl_amount1.setText("AMOUNT:");

        tp_f_btn_confirm2.setBackground(new java.awt.Color(0, 0, 0));
        tp_f_btn_confirm2.setForeground(new java.awt.Color(255, 255, 255));
        tp_f_btn_confirm2.setText("CONFIRM");
        tp_f_btn_confirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_f_btn_confirm2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("9");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("5");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("3");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setText("8");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton8.setText("7");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton9.setText("6");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 128)); // NOI18N
        jLabel2.setText("P1,000.01");

        jLabel1.setText("BALANCE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jButton10.setText("reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton11.setText("0");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEPOSIT", "WITHDRAW" }));

        tp_f_lbl_source2.setText("TRANSACTION:");

        javax.swing.GroupLayout tp_transLayout = new javax.swing.GroupLayout(tp_trans);
        tp_trans.setLayout(tp_transLayout);
        tp_transLayout.setHorizontalGroup(
            tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_transLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tp_f_btn_confirm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_transLayout.createSequentialGroup()
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_lbl_source1)
                            .addComponent(tp_f_t_source1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_lbl_amount1)
                            .addComponent(tp_f_t_amount1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_transLayout.createSequentialGroup()
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_transLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tp_transLayout.createSequentialGroup()
                                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tp_transLayout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(tp_transLayout.createSequentialGroup()
                                                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(tp_transLayout.createSequentialGroup()
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_transLayout.createSequentialGroup()
                                .addComponent(tp_f_lbl_source2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tp_transLayout.setVerticalGroup(
            tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_transLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tp_transLayout.createSequentialGroup()
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tp_f_lbl_source1)
                            .addComponent(tp_f_lbl_amount1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tp_f_t_source1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tp_f_t_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tp_f_lbl_source2))
                        .addGap(27, 27, 27)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(tp_f_btn_confirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tp.addTab("deposit/withdraw", tp_trans);

        tp_settings.setBackground(new java.awt.Color(255, 255, 255));

        tp_s_btn_info.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_info.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_info.setText("UPDATE INFORMATION");

        tp_s_btn_pass.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_pass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_pass.setText("CHANGE PASSWORD");

        tp_s_btn_logout.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_logout.setText("LOG OUT");

        tp_s_btn_logout1.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_logout1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_logout1.setText("CLOSE ACCOUNT");

        tp_s_btn_pass1.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_pass1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_pass1.setText("CHANGE SECURITY QUESTIONS");

        javax.swing.GroupLayout tp_settingsLayout = new javax.swing.GroupLayout(tp_settings);
        tp_settings.setLayout(tp_settingsLayout);
        tp_settingsLayout.setHorizontalGroup(
            tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_s_btn_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_logout1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_pass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE))
                .addContainerGap())
        );
        tp_settingsLayout.setVerticalGroup(
            tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_s_btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tp_s_btn_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        tp.addTab("settings", tp_settings);

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setForeground(new java.awt.Color(102, 102, 102));
        btn5.setText("SETTINGS");
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        tp.setSelectedIndex(0);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        tp.setSelectedIndex(1);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        tp.setSelectedIndex(2);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        tp.setSelectedIndex(3);
    }//GEN-LAST:event_btn5ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+5);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+6);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+7);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+8);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+9);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        tp_f_t_amount1.setText(tp_f_t_amount1.getText()+0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        tp_f_t_amount1.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tp_f_btn_confirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_f_btn_confirm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tp_f_btn_confirm2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JTabbedPane tp;
    private javax.swing.JScrollPane tp_b_scrollpane;
    private javax.swing.JTable tp_b_table;
    private javax.swing.JPanel tp_balance;
    private javax.swing.JButton tp_f_btn_confirm;
    private javax.swing.JButton tp_f_btn_confirm2;
    private javax.swing.JLabel tp_f_lbl_amount;
    private javax.swing.JLabel tp_f_lbl_amount1;
    private javax.swing.JLabel tp_f_lbl_dest;
    private javax.swing.JLabel tp_f_lbl_notes;
    private javax.swing.JLabel tp_f_lbl_source;
    private javax.swing.JLabel tp_f_lbl_source1;
    private javax.swing.JLabel tp_f_lbl_source2;
    private javax.swing.JScrollPane tp_f_scrollpane;
    private javax.swing.JTextField tp_f_t_amount;
    private javax.swing.JTextField tp_f_t_amount1;
    private javax.swing.JTextField tp_f_t_dest;
    private javax.swing.JTextArea tp_f_t_notes;
    private javax.swing.JComboBox<String> tp_f_t_source;
    private javax.swing.JComboBox<String> tp_f_t_source1;
    private javax.swing.JPanel tp_funds;
    private javax.swing.JButton tp_s_btn_info;
    private javax.swing.JButton tp_s_btn_logout;
    private javax.swing.JButton tp_s_btn_logout1;
    private javax.swing.JButton tp_s_btn_pass;
    private javax.swing.JButton tp_s_btn_pass1;
    private javax.swing.JPanel tp_settings;
    private javax.swing.JButton tp_t_btn_set;
    private javax.swing.JLabel tp_t_lbl_from;
    private javax.swing.JLabel tp_t_lbl_to;
    private javax.swing.JScrollPane tp_t_scrollpane;
    private javax.swing.JSpinner tp_t_spin_from_day;
    private javax.swing.JSpinner tp_t_spin_from_month;
    private javax.swing.JSpinner tp_t_spin_from_year;
    private javax.swing.JSpinner tp_t_spin_to_day;
    private javax.swing.JSpinner tp_t_spin_to_month;
    private javax.swing.JSpinner tp_t_spin_to_year;
    private javax.swing.JTable tp_t_table;
    private javax.swing.JPanel tp_trans;
    // End of variables declaration//GEN-END:variables
}
